name: zip and upload
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  zip_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip files
        run: zip -r function-source.zip *

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
  
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
  
      - name: Upload to Cloud Storage
        run: gcloud storage cp function-source.zip gs://gcf-code-bucket